include(${CMAKE_CURRENT_LIST_DIR}/utility.cmake)

macro(cmtk_add_test_subdirectory_if_build dir_name)
  cmake_parse_arguments("M_ARG" "" "NAME;BUILD_OPTION_NAME;BUILD_OPTION_MSG;BUILD_OPTION_DEFAULT" "" ${ARGN})
  set_ifndef(M_ARG_NAME "${PROJECT_NAME}")
  if(NOT M_ARG_BUILD_OPTION_NAME)
    make_upper_c_identifier("${M_ARG_NAME}" upper_var_name)
    set(M_ARG_BUILD_OPTION_NAME "BUILD_${upper_var_name}_TESTS")
  endif()
  set_ifndef(M_ARG_BUILD_OPTION_MSG "Build ${M_ARG_NAME} tests or not.")
  set_ifndef(M_ARG_BUILD_OPTION_DEFAULT OFF)
  fatal_if_none_of(M_ARG_BUILD_OPTION_DEFAULT "ON" "OFF")
  option(${M_ARG_BUILD_OPTION_NAME} ${M_ARG_BUILD_OPTION_MSG} ${M_ARG_BUILD_OPTION_DEFAULT})
  if(${M_ARG_BUILD_OPTION_NAME})
    include(CTest)
    if(BUILD_TESTING)
      add_subdirectory(${dir_name})
    endif()
  endif()
endmacro()
