include(${CMAKE_CURRENT_LIST_DIR}/utility.cmake)

# cmtk_set_logging_level_ifndef()
function(cmtk_set_logging_level_ifndef out_var)
    set(options "")
    set(params "BUILD_TYPE")
    set(lists "BUILD_TYPES;LEVELS;VALUES")
    cmake_parse_arguments(PARSE_ARGV 1 "ARG" "${options}" "${params}" "${lists}")
    cmtk_set_ifndef(ARG_BUILD_TYPES "Debug;Release")
    cmtk_set_ifndef(ARG_LEVELS "DEBUG;INFO")
    list(LENGTH ARG_BUILD_TYPES nb_build_types)
    list(LENGTH ARG_LEVELS nb_levels)
    cmtk_assert(nb_build_types EQUAL nb_levels)
    cmtk_set_ifndef(ARG_VALUES "TRACE;DEBUG;INFO;WARN;ERROR;CRITICAL;OFF")
    if(NOT DEFINED ${out_var})
        set(level "TRACE")
        cmtk_set_ifndef(ARG_BUILD_TYPE ${CMAKE_BUILD_TYPE})
        if(ARG_BUILD_TYPE)
            list(FIND ARG_BUILD_TYPES "${ARG_BUILD_TYPE}" bt_index)
            if(NOT bt_index EQUAL -1)
                list(GET ARG_LEVELS ${bt_index} level)
            endif()
        endif()
        set(${out_var} "${level}" CACHE STRING "Choose the level of logging.")
        set_property(CACHE ${out_var} PROPERTY STRINGS ${ARG_VALUES})
    endif()
endfunction()
